# INFO: Checkout https://github.com/helix-editor/helix/wiki/Language-Server-Configurations for more LSP Configuration/Setup

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html"]
# roots = []
# auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "css"
# scope = "source.css"
injection-regex = "css"
file-types = ["css", "scss"]
roots = []
# auto-format = true
indent = { tab-width = 4, unit = "    " }

# CUSTOM LSP (use your pkg manager instead, e.g. brew install vue-language-server, helix will auto-detect it usually)
# [[language]]
# name = "vue"
# auto-format = true
# formatter = { command = "prettier", args = ["--parser", "vue"] }
# language-servers = ["typescript-language-server"]

# [[language-server.typescript-language-server.config.plugins]]
# name = "@vue/typescript-plugin"
# location = "/opt/homebrew/lib/node_modules/@vue/language-server" # INFO: Replace PATH with your LSP
# languages = ["vue"]

